# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.news import News
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class NewsList(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, news: List[News]=None):
        """
        NewsList - a model defined in Swagger

        :param news: The news of this NewsList.
        :type news: List[News]
        """
        self.swagger_types = {
            'news': List[News]
        }

        self.attribute_map = {
            'news': 'news'
        }

        self._news = news

    @classmethod
    def from_dict(cls, dikt) -> 'NewsList':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NewsList of this NewsList.
        :rtype: NewsList
        """
        return deserialize_model(dikt, cls)

    @property
    def news(self) -> List[News]:
        """
        Gets the news of this NewsList.
        List of all sites.

        :return: The news of this NewsList.
        :rtype: List[News]
        """
        return self._news

    @news.setter
    def news(self, news: List[News]):
        """
        Sets the news of this NewsList.
        List of all sites.

        :param news: The news of this NewsList.
        :type news: List[News]
        """

        self._news = news

