# coding: utf-8

from __future__ import absolute_import
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Site(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, site_id: int=None, name: str=None, url: str=None):
        """
        Site - a model defined in Swagger

        :param site_id: The site_id of this Site.
        :type site_id: int
        :param name: The name of this Site.
        :type name: str
        :param url: The url of this Site.
        :type url: str
        """
        self.swagger_types = {
            'site_id': int,
            'name': str,
            'url': str
        }

        self.attribute_map = {
            'site_id': 'siteId',
            'name': 'name',
            'url': 'url'
        }

        self._site_id = site_id
        self._name = name
        self._url = url

    @classmethod
    def from_dict(cls, dikt) -> 'Site':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Site of this Site.
        :rtype: Site
        """
        return deserialize_model(dikt, cls)

    @property
    def site_id(self) -> int:
        """
        Gets the site_id of this Site.

        :return: The site_id of this Site.
        :rtype: int
        """
        return self._site_id

    @site_id.setter
    def site_id(self, site_id: int):
        """
        Sets the site_id of this Site.

        :param site_id: The site_id of this Site.
        :type site_id: int
        """

        self._site_id = site_id

    @property
    def name(self) -> str:
        """
        Gets the name of this Site.

        :return: The name of this Site.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Site.

        :param name: The name of this Site.
        :type name: str
        """

        self._name = name

    @property
    def url(self) -> str:
        """
        Gets the url of this Site.

        :return: The url of this Site.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url: str):
        """
        Sets the url of this Site.

        :param url: The url of this Site.
        :type url: str
        """

        self._url = url

