# coding: utf-8

from __future__ import absolute_import
from swagger_server.models.site import Site
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class SiteList(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, sites: List[Site]=None):
        """
        SiteList - a model defined in Swagger

        :param sites: The sites of this SiteList.
        :type sites: List[Site]
        """
        self.swagger_types = {
            'sites': List[Site]
        }

        self.attribute_map = {
            'sites': 'sites'
        }

        self._sites = sites

    @classmethod
    def from_dict(cls, dikt) -> 'SiteList':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SiteList of this SiteList.
        :rtype: SiteList
        """
        return deserialize_model(dikt, cls)

    @property
    def sites(self) -> List[Site]:
        """
        Gets the sites of this SiteList.
        List of all sites.

        :return: The sites of this SiteList.
        :rtype: List[Site]
        """
        return self._sites

    @sites.setter
    def sites(self, sites: List[Site]):
        """
        Sets the sites of this SiteList.
        List of all sites.

        :param sites: The sites of this SiteList.
        :type sites: List[Site]
        """

        self._sites = sites

